export const DEFAULT_DATE_OPTIONS = {
	all: {
		name: 'All',
		iconName: 'stacks',
		selected: true,
		fromDate: null,
		toDate: null,
	},
	noDate: {
		name: 'No Date',
		iconName: 'hourglass_empty',
		selected: false,
		fromDate: null,
		toDate: null,
	},
	overdue: {
		name: 'Overdue',
		iconName: 'west',
		selected: false,
		fromDate: null,
		toDate: null,
	},
	repeat: {
		name: 'Repeat',
		iconName: 'repeat',
		selected: false,
		fromDate: null,
		toDate: null,
	},
	today: {
		name: 'Today',
		iconName: 'calendar_today',
		selected: false,
		fromDate: null,
		toDate: null,
	},
	tomorrow: {
		name: 'Tomorrow',
		iconName: 'upcoming',
		selected: false,
		fromDate: null,
		toDate: null,
	},
	thisWeek: {
		name: 'This Week',
		iconName: 'event_upcoming',
		selected: false,
		fromDate: null,
		toDate: null,
	},
	nextWeek: {
		name: 'Next Week',
		iconName: 'stacks',
		selected: false,
		fromDate: null,
		toDate: null,
	},
	thisMonth: {
		name: 'This Month',
		iconName: 'dark_mode',
		selected: false,
		fromDate: null,
		toDate: null,
	},
	nextMonth: {
		name: 'Next Month',
		iconName: 'nights_stay',
		selected: false,
		fromDate: null,
		toDate: null,
	},
	duration: {
		name: 'Duration',
		iconName: 'timer',
		selected: false,
		fromDate: '2024-06-21T04:00:00.000Z',
		toDate: '2024-06-29T04:00:00.000Z',
	},
};
